name: Code Quality

on: [push, pull_request]

jobs:
  quality:
    uses: frasermolyneux/actions/.github/workflows/codequality.yml@main
    with:
      sonar-project-key: frasermolyneux_api-client-abstractions
      sonar-organization: frasermolyneux
      sonar-host-url: https://sonarcloud.io
      build-target: dotnet-ci
      dotnet-version: |
        9.0.x
        10.0.x-preview
      src-folder: src
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
